# example profiles.yml file
Luc:
  target: prod
  outputs:
    prod:
      type: mysql
      host: localhost
      user: Luc
      password: <password>
      port: 5432
      dbname: formula_1
      schema: dbt_luc
      threads: 4