version: 2

sources:
  - name: staging
    description: "This is a replica -minus some useless columns- of the source CSV files"

    tables:
      - name: stg_circuits
        description: "Contains information about the different circuits used"
      - name: stg_constructor_results
        description: "Describes the result obtained by each constructor at each race"

      - name: stg_constructor_standings
        description: "Describes the standings for each constructos at each race"

      - name: stg_constructor
        description: "Contains information about each constructor"

      - name: stg_driver_standings
        description: "Describe the standings for each driver at each race"

      - name: stg_drivers
        description: "Contains information about each driver"

      - name: stg_lap_times
        description: "Contains information about each lap time at each race"

      - name: stg_races
        description: "Contains information about each race"

      - name: stg_results
        description: "Describes results at each race"

      - name: stg_seasons
        description: "Contains information about each season"

      - name: stg_sprint_results
        description: "Describes results for each sprint race"

      - name: stg_status
        description: "Contains information about each status (reasons why a drive did not finish its race)"

      - name: stg_pit_stops
        description: "Contains information about each pit stop for each race"

      - name: stg_qualifying
        description: "Contains information about each qualifying session"
